name: Build DMG

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build macOS app bundle with PyInstaller
      run: |
        pyinstaller --onefile --windowed Script_final/Main.py --name BS_Reconciliation_APP

    - name: Create DMG from app bundle
      run: |
        mkdir -p dmg
        # Create a temporary directory for the app bundle
        APP_BUNDLE=dist/BS_Reconciliation_APP.app
        DMG_PATH=dmg/BS_Reconciliation_APP.dmg
        # Use hdiutil to create the DMG
        hdiutil create -volname BS_Reconciliation_APP -srcfolder "$APP_BUNDLE" -ov -format UDZO "$DMG_PATH"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: BS_Reconciliation_APP_DMG
        path: dmg/BS_Reconciliation_APP.dmg
